name: check dates in README
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
