---
name: check dates in README
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - run: |
          python .github/scripts/check_dates.py
        env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
